# Generated by Django 5.2.6 on 2025-12-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='acrescimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DIN', 'Dinheiro'), ('CRE', 'Cartão de Crédito'), ('DEB', 'Cartão de Débito'), ('PIX', 'Pix')], default='DIN', max_length=3),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído'), ('X', 'Cancelado')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
