# Generated by Django 5.2.6 on 2025-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensvenda',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
