# Generated by Django 5.2.6 on 2025-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_itensvenda_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_venda',
            field=models.CharField(choices=[('UN', 'Unidade (Inteiro)'), ('FR', 'Fração / Metro / Kg (Decimal)')], default='UN', max_length=2, verbose_name='Tipo de Venda'),
        ),
    ]
