# Generated by Django 5.2.6 on 2025-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_produto_tipo_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
