# Generated by Django 5.2.6 on 2025-12-11 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
