# Generated by Django 5.2.6 on 2025-12-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
