# Generated by Django 5.2.6 on 2025-12-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_venda_valor_recebido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
